create table RGS_Register (
	uuid_ VARCHAR(75) null,
	registerId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	first_name VARCHAR(75) null,
	last_name VARCHAR(75) null,
	email_address VARCHAR(75) null,
	user_name VARCHAR(75) null,
	birthday DATE null,
	gender VARCHAR(75) null,
	password2 VARCHAR(75) null,
	home_phone LONG,
	mobile_phone LONG,
	address VARCHAR(75) null,
	address2 VARCHAR(75) null,
	city VARCHAR(75) null,
	state_ VARCHAR(75) null,
	zip VARCHAR(75) null,
	security_question VARCHAR(75) null,
	security_answer VARCHAR(75) null,
	accepted_tou BOOLEAN,
	status INTEGER,
	statusByUserId LONG,
	statusByUserName VARCHAR(75) null,
	statusDate DATE null
);