/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.assignment.registration.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.model.WorkflowedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Register service. Represents a row in the &quot;RGS_Register&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.assignment.registration.model.impl.RegisterModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.assignment.registration.model.impl.RegisterImpl</code>.
 * </p>
 *
 * @author tarun
 * @see Register
 * @generated
 */
@ProviderType
public interface RegisterModel
	extends BaseModel<Register>, GroupedModel, ShardedModel, StagedAuditedModel,
			WorkflowedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a register model instance should use the {@link Register} interface instead.
	 */

	/**
	 * Returns the primary key of this register.
	 *
	 * @return the primary key of this register
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this register.
	 *
	 * @param primaryKey the primary key of this register
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this register.
	 *
	 * @return the uuid of this register
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this register.
	 *
	 * @param uuid the uuid of this register
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the register ID of this register.
	 *
	 * @return the register ID of this register
	 */
	public long getRegisterId();

	/**
	 * Sets the register ID of this register.
	 *
	 * @param registerId the register ID of this register
	 */
	public void setRegisterId(long registerId);

	/**
	 * Returns the group ID of this register.
	 *
	 * @return the group ID of this register
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this register.
	 *
	 * @param groupId the group ID of this register
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this register.
	 *
	 * @return the company ID of this register
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this register.
	 *
	 * @param companyId the company ID of this register
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this register.
	 *
	 * @return the user ID of this register
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this register.
	 *
	 * @param userId the user ID of this register
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this register.
	 *
	 * @return the user uuid of this register
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this register.
	 *
	 * @param userUuid the user uuid of this register
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this register.
	 *
	 * @return the user name of this register
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this register.
	 *
	 * @param userName the user name of this register
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this register.
	 *
	 * @return the create date of this register
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this register.
	 *
	 * @param createDate the create date of this register
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this register.
	 *
	 * @return the modified date of this register
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this register.
	 *
	 * @param modifiedDate the modified date of this register
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the first_name of this register.
	 *
	 * @return the first_name of this register
	 */
	@AutoEscape
	public String getFirst_name();

	/**
	 * Sets the first_name of this register.
	 *
	 * @param first_name the first_name of this register
	 */
	public void setFirst_name(String first_name);

	/**
	 * Returns the last_name of this register.
	 *
	 * @return the last_name of this register
	 */
	@AutoEscape
	public String getLast_name();

	/**
	 * Sets the last_name of this register.
	 *
	 * @param last_name the last_name of this register
	 */
	public void setLast_name(String last_name);

	/**
	 * Returns the email_address of this register.
	 *
	 * @return the email_address of this register
	 */
	@AutoEscape
	public String getEmail_address();

	/**
	 * Sets the email_address of this register.
	 *
	 * @param email_address the email_address of this register
	 */
	public void setEmail_address(String email_address);

	/**
	 * Returns the user_name of this register.
	 *
	 * @return the user_name of this register
	 */
	@AutoEscape
	public String getUser_name();

	/**
	 * Sets the user_name of this register.
	 *
	 * @param user_name the user_name of this register
	 */
	public void setUser_name(String user_name);

	/**
	 * Returns the birthday of this register.
	 *
	 * @return the birthday of this register
	 */
	public Date getBirthday();

	/**
	 * Sets the birthday of this register.
	 *
	 * @param birthday the birthday of this register
	 */
	public void setBirthday(Date birthday);

	/**
	 * Returns the gender of this register.
	 *
	 * @return the gender of this register
	 */
	@AutoEscape
	public String getGender();

	/**
	 * Sets the gender of this register.
	 *
	 * @param gender the gender of this register
	 */
	public void setGender(String gender);

	/**
	 * Returns the password2 of this register.
	 *
	 * @return the password2 of this register
	 */
	@AutoEscape
	public String getPassword2();

	/**
	 * Sets the password2 of this register.
	 *
	 * @param password2 the password2 of this register
	 */
	public void setPassword2(String password2);

	/**
	 * Returns the home_phone of this register.
	 *
	 * @return the home_phone of this register
	 */
	public Long getHome_phone();

	/**
	 * Sets the home_phone of this register.
	 *
	 * @param home_phone the home_phone of this register
	 */
	public void setHome_phone(Long home_phone);

	/**
	 * Returns the mobile_phone of this register.
	 *
	 * @return the mobile_phone of this register
	 */
	public Long getMobile_phone();

	/**
	 * Sets the mobile_phone of this register.
	 *
	 * @param mobile_phone the mobile_phone of this register
	 */
	public void setMobile_phone(Long mobile_phone);

	/**
	 * Returns the address of this register.
	 *
	 * @return the address of this register
	 */
	@AutoEscape
	public String getAddress();

	/**
	 * Sets the address of this register.
	 *
	 * @param address the address of this register
	 */
	public void setAddress(String address);

	/**
	 * Returns the address2 of this register.
	 *
	 * @return the address2 of this register
	 */
	@AutoEscape
	public String getAddress2();

	/**
	 * Sets the address2 of this register.
	 *
	 * @param address2 the address2 of this register
	 */
	public void setAddress2(String address2);

	/**
	 * Returns the city of this register.
	 *
	 * @return the city of this register
	 */
	@AutoEscape
	public String getCity();

	/**
	 * Sets the city of this register.
	 *
	 * @param city the city of this register
	 */
	public void setCity(String city);

	/**
	 * Returns the state of this register.
	 *
	 * @return the state of this register
	 */
	@AutoEscape
	public String getState();

	/**
	 * Sets the state of this register.
	 *
	 * @param state the state of this register
	 */
	public void setState(String state);

	/**
	 * Returns the zip of this register.
	 *
	 * @return the zip of this register
	 */
	@AutoEscape
	public String getZip();

	/**
	 * Sets the zip of this register.
	 *
	 * @param zip the zip of this register
	 */
	public void setZip(String zip);

	/**
	 * Returns the security_question of this register.
	 *
	 * @return the security_question of this register
	 */
	@AutoEscape
	public String getSecurity_question();

	/**
	 * Sets the security_question of this register.
	 *
	 * @param security_question the security_question of this register
	 */
	public void setSecurity_question(String security_question);

	/**
	 * Returns the security_answer of this register.
	 *
	 * @return the security_answer of this register
	 */
	@AutoEscape
	public String getSecurity_answer();

	/**
	 * Sets the security_answer of this register.
	 *
	 * @param security_answer the security_answer of this register
	 */
	public void setSecurity_answer(String security_answer);

	/**
	 * Returns the accepted_tou of this register.
	 *
	 * @return the accepted_tou of this register
	 */
	public boolean getAccepted_tou();

	/**
	 * Returns <code>true</code> if this register is accepted_tou.
	 *
	 * @return <code>true</code> if this register is accepted_tou; <code>false</code> otherwise
	 */
	public boolean isAccepted_tou();

	/**
	 * Sets whether this register is accepted_tou.
	 *
	 * @param accepted_tou the accepted_tou of this register
	 */
	public void setAccepted_tou(boolean accepted_tou);

	/**
	 * Returns the status of this register.
	 *
	 * @return the status of this register
	 */
	@Override
	public int getStatus();

	/**
	 * Sets the status of this register.
	 *
	 * @param status the status of this register
	 */
	@Override
	public void setStatus(int status);

	/**
	 * Returns the status by user ID of this register.
	 *
	 * @return the status by user ID of this register
	 */
	@Override
	public long getStatusByUserId();

	/**
	 * Sets the status by user ID of this register.
	 *
	 * @param statusByUserId the status by user ID of this register
	 */
	@Override
	public void setStatusByUserId(long statusByUserId);

	/**
	 * Returns the status by user uuid of this register.
	 *
	 * @return the status by user uuid of this register
	 */
	@Override
	public String getStatusByUserUuid();

	/**
	 * Sets the status by user uuid of this register.
	 *
	 * @param statusByUserUuid the status by user uuid of this register
	 */
	@Override
	public void setStatusByUserUuid(String statusByUserUuid);

	/**
	 * Returns the status by user name of this register.
	 *
	 * @return the status by user name of this register
	 */
	@AutoEscape
	@Override
	public String getStatusByUserName();

	/**
	 * Sets the status by user name of this register.
	 *
	 * @param statusByUserName the status by user name of this register
	 */
	@Override
	public void setStatusByUserName(String statusByUserName);

	/**
	 * Returns the status date of this register.
	 *
	 * @return the status date of this register
	 */
	@Override
	public Date getStatusDate();

	/**
	 * Sets the status date of this register.
	 *
	 * @param statusDate the status date of this register
	 */
	@Override
	public void setStatusDate(Date statusDate);

	/**
	 * Returns <code>true</code> if this register is approved.
	 *
	 * @return <code>true</code> if this register is approved; <code>false</code> otherwise
	 */
	@Override
	public boolean isApproved();

	/**
	 * Returns <code>true</code> if this register is denied.
	 *
	 * @return <code>true</code> if this register is denied; <code>false</code> otherwise
	 */
	@Override
	public boolean isDenied();

	/**
	 * Returns <code>true</code> if this register is a draft.
	 *
	 * @return <code>true</code> if this register is a draft; <code>false</code> otherwise
	 */
	@Override
	public boolean isDraft();

	/**
	 * Returns <code>true</code> if this register is expired.
	 *
	 * @return <code>true</code> if this register is expired; <code>false</code> otherwise
	 */
	@Override
	public boolean isExpired();

	/**
	 * Returns <code>true</code> if this register is inactive.
	 *
	 * @return <code>true</code> if this register is inactive; <code>false</code> otherwise
	 */
	@Override
	public boolean isInactive();

	/**
	 * Returns <code>true</code> if this register is incomplete.
	 *
	 * @return <code>true</code> if this register is incomplete; <code>false</code> otherwise
	 */
	@Override
	public boolean isIncomplete();

	/**
	 * Returns <code>true</code> if this register is pending.
	 *
	 * @return <code>true</code> if this register is pending; <code>false</code> otherwise
	 */
	@Override
	public boolean isPending();

	/**
	 * Returns <code>true</code> if this register is scheduled.
	 *
	 * @return <code>true</code> if this register is scheduled; <code>false</code> otherwise
	 */
	@Override
	public boolean isScheduled();

}